version: "1.0"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty

  node:
    build: .
    container_name: node
    ports:
    - "3000:3000"
    environment:
      MONGO_DB_USERNAME: admin
      MONGO_DB_PASSWORD: qwerty
    depends_on:
      - mongo